docker-defaults: &docker-defaults
  docker:
    - image: quay.io/nyulibraries/circleci_docker:18.06.3-dc-1.23.2-0
  working_directory: ~/app

version: 2
jobs:
  run-views-e2e-tests:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull Cache Image & Tag
          command: |
            docker pull quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:pt-3
            docker pull quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:e2e
            docker tag quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:pt-3 primo-explore-eluna-workshop-pt-4
            docker tag quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:e2e primo-explore-eluna-cypress
      - run:
          name: Run View E2E Tests
          command: |
            docker-compose build web
            script/run_view_e2e_tests.sh
      - store_artifacts:
          path: cypress-results
      - store_test_results:
          path: cypress-results/test-results

  create-view-packages:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull Cache Image & Tag
          command: |
            docker pull quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:pt-3
            docker tag quay.io/nyulibraries/eluna-2019-devday-advanced-workshop:pt-3 primo-explore-eluna-workshop-pt-4
      - run:
          name: Build asset VIEW package and store
          command: script/create_view_packages.sh
      - store_artifacts:
          path: packages

workflows:
  version: 2
  build-test-and-deliver:
    jobs:
    - run-views-e2e-tests
    - create-view-packages:
        requires:
        - run-views-e2e-tests

